version: '3.8'

services:
  app:
    build: .
    # 直接暴露 3001 端口到容器的 3000 端口
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - QIANFAN_API_KEY=${QIANFAN_API_KEY}
      - QIANFAN_APP_ID=${QIANFAN_APP_ID}
    restart: unless-stopped
    # 我们暂时保留健康检查，但它不再影响外部访问
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 