version: '3.8'

networks:
  traefik_default:
    external: true

services:
  app:
    build: .
    networks:
      - traefik_default
    # ports:
    #   - "3001:3000" # Traefik会处理端口，不再需要直接暴露
    environment:
      - NODE_ENV=production
      - PORT=3000
      - QIANFAN_API_KEY=${QIANFAN_API_KEY}
      - QIANFAN_APP_ID=${QIANFAN_APP_ID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jimei-server.rule=Host(`parking.ketuzx.com`)"
      - "traefik.http.routers.jimei-server.tls=true"
      - "traefik.http.routers.jimei-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.jimei-server.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"

  # 可选：如果需要Redis缓存
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data
  #   command: redis-server --appendonly yes

# volumes:
#   redis_data: 